### ISSUE TITLE
yeah! Baby,你怎么知道大家都想把SoVITS迁移到comfyui中这个巨大生态中来？

### ISSUE THREAD

**Issue by Pythonpa** [AIFSH/ComfyUI-GPT_SoVITS#1]
yeah! Baby,你怎么知道大家都想把SoVITS迁移到comfyui中这个巨大生态中来？
加油，看好你哦~~先提前把
![01274858](https://github.com/AIFSH/ComfyUI-GPT_SoVITS/assets/16030016/f6efd7ff-acf8-4de9-a95c-8e1f7f800374)
g给预定了。

**Comment by AIFSH** [comment]
敬请期待
