### ISSUE TITLE
这两个参数的权重无法读取

### ISSUE THREAD

**Issue by hanL34** [AIFSH/ComfyUI-GPT_SoVITS#10]
![image](https://github.com/AIFSH/ComfyUI-GPT_SoVITS/assets/127322778/08a2c8fa-571d-416a-9635-ac9ba0c152c3)

**Comment by AIFSH** [comment]
这个教程请一帧帧看，仔细看

【交错战线PV「哈托莉」AI配音 | 我用ComfyUI来做同声传译-哔哩哔哩】 https://b23.tv/nZvnrWf
