### ISSUE TITLE
is a 'q'  missing  in the name of 'requirements.txt'？

### ISSUE THREAD

**Issue by escalate007** [AIFSH/ComfyUI-GPT_SoVITS#2]
![火狐截图_2024-04-13T09-02-52 573Z](https://github.com/AIFSH/ComfyUI-GPT_SoVITS/assets/55056146/328ae31b-0d75-456e-927a-d4725de445b1)
I tried to install the requirement but failed，found a 'q' which is missing in its name.

**Comment by AIFSH** [comment]
thanks,next  push will rename it

**Comment by 602387193c** [comment]
都中国人，说什么英语？
