### ISSUE TITLE
install requirements error

### ISSUE THREAD

**Issue by PetitPrinceb612** [AIFSH/ComfyUI-GPT_SoVITS#9]
Hello, I got an error when installing requirements. Is there any way to solve it?

`C:\other\ai\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GPT_SoVITS-main>pip install -r requirements.txt
Collecting pydub (from -r requirements.txt (line 1))
  Using cached pydub-0.25.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting srt (from -r requirements.txt (line 2))
  Using cached srt-3.5.3.tar.gz (28 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: librosa in c:\users\w8096\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 3)) (0.10.1)
Collecting LangSegment (from -r requirements.txt (line 4))
  Using cached LangSegment-0.3.3-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: transformers in c:\users\w8096\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 5)) (4.38.2)
Collecting cn2an (from -r requirements.txt (line 6))
  Using cached cn2an-0.5.22-py3-none-any.whl.metadata (10 kB)
Collecting pypinyin (from -r requirements.txt (line 7))
  Using cached pypinyin-0.51.0-py2.py3-none-any.whl.metadata (12 kB)
Collecting jieba_fast (from -r requirements.txt (line 8))
  Using cached jieba_fast-0.53.tar.gz (7.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pyopenjtalk (from -r requirements.txt (line 9))
  Using cached pyopenjtalk-0.3.3.tar.gz (1.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      setup.py:26: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        _CYTHON_INSTALLED = ver >= LooseVersion(min_cython_ver)
      -- Building for: NMake Makefiles
      CMake Deprecation Warning at CMakeLists.txt:5 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.

      CMake Error at CMakeLists.txt:17 (project):
        Running

         'nmake' '-?'

        failed with:

         no such file or directory

      CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
      CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
      -- Configuring incomplete, errors occurred!
      CMake is in the system path. Version:               cmake version 3.29.2

      CMake suite maintained and supported by Kitware (kitware.com/cmake).
      Traceback (most recent call last):
        File "C:\Users\w8096\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\w8096\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\w8096\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\w8096\AppData\Local\Temp\pip-build-env-02nzimpi\overlay\Lib\site-packages\setuptools\build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "C:\Users\w8096\AppData\Local\Temp\pip-build-env-02nzimpi\overlay\Lib\site-packages\setuptools\build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "C:\Users\w8096\AppData\Local\Temp\pip-build-env-02nzimpi\overlay\Lib\site-packages\setuptools\build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 191, in <module>
        File "C:\Users\w8096\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 456, in check_returncode
          raise CalledProcessError(self.returncode, self.args, self.stdout,
      subprocess.CalledProcessError: Command '['cmake', '..', '-DHTS_ENGINE_INCLUDE_DIR=.', '-DHTS_ENGINE_LIB=dummy']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

**Comment by AIFSH** [comment]
you may need this

【东哥视频翻译工作流Windows一键包来啦！-哔哩哔哩】 https://b23.tv/C40WQV8
